"""core architecture

Revision ID: 0001
Revises:
Create Date: 2026-09-12 12:07:46.977571
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=120), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column("entry_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_hash"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_resource_id"), "audit_logs", ["resource_id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_resource_type"), "audit_logs", ["resource_type"], unique=False
    )
    op.create_index(
        "ix_audit_resource", "audit_logs", ["resource_type", "resource_id"], unique=False
    )
    op.create_table(
        "diseases",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "idempotency_receipts",
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=80), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("actor_id", "idempotency_key", name="uq_idempotency_actor_key"),
    )
    op.create_table(
        "locations",
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("hierarchy_path", sa.String(length=500), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "level IN ('COUNTRY', 'STATE', 'DISTRICT', 'BLOCK', 'VILLAGE')",
            name="ck_locations_level",
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        "ix_locations_geometry_gist",
        "locations",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_locations_hierarchy_path"), "locations", ["hierarchy_path"], unique=False
    )
    op.create_table(
        "outbox_events",
        sa.Column("topic", sa.String(length=160), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_id"), "outbox_events", ["aggregate_id"], unique=False
    )
    op.create_index(op.f("ix_outbox_events_topic"), "outbox_events", ["topic"], unique=False)
    op.create_index(
        "ix_outbox_pending", "outbox_events", ["published_at", "created_at"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=240), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "code IN ('FARMER', 'PARAVET', 'VETERINARIAN', 'LAB_TECHNICIAN', 'DISTRICT_OFFICER', 'ADMIN')",
            name="ck_roles_code",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "symptoms",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("severity BETWEEN 1 AND 5", name="ck_symptoms_severity"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("user_type", sa.String(length=16), nullable=False),
        sa.Column("mobile_number", sa.String(length=20), nullable=True),
        sa.Column("staff_identifier", sa.String(length=80), nullable=True),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(user_type = 'FARMER' AND mobile_number IS NOT NULL) OR (user_type = 'STAFF' AND staff_identifier IS NOT NULL)",
            name="ck_users_identity",
        ),
        sa.CheckConstraint("user_type IN ('FARMER', 'STAFF')", name="ck_users_type"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mobile_number"),
        sa.UniqueConstraint("staff_identifier"),
    )
    op.create_table(
        "auth_identities",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "disease_symptoms",
        sa.Column("disease_id", sa.Uuid(), nullable=False),
        sa.Column("symptom_id", sa.Uuid(), nullable=False),
        sa.Column("default_weight", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.ForeignKeyConstraint(["disease_id"], ["diseases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["symptom_id"], ["symptoms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("disease_id", "symptom_id"),
    )
    op.create_table(
        "farms",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_farms_geometry_gist", "farms", ["geometry"], unique=False, postgresql_using="gist"
    )
    op.create_index(op.f("ix_farms_location_id"), "farms", ["location_id"], unique=False)
    op.create_index(op.f("ix_farms_owner_id"), "farms", ["owner_id"], unique=False)
    op.create_table(
        "mfa_credentials",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("totp_secret_encrypted", sa.String(length=512), nullable=False),
        sa.Column("recovery_code_hashes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "outbreaks",
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("disease_code", sa.String(length=60), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("config_version", sa.String(length=80), nullable=False),
        sa.Column("score", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "cluster_geometry",
            geoalchemy2.types.Geometry(
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("declared_by_id", sa.Uuid(), nullable=True),
        sa.Column("declared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('POTENTIAL', 'DECLARED', 'DISMISSED', 'CLOSED')", name="ck_outbreaks_state"
        ),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name="ck_outbreaks_score_range"),
        sa.ForeignKeyConstraint(["declared_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_outbreak_geometry_gist",
        "outbreaks",
        ["cluster_geometry"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index("ix_outbreak_state_created", "outbreaks", ["state", "created_at"], unique=False)
    op.create_index(op.f("ix_outbreaks_disease_code"), "outbreaks", ["disease_code"], unique=False)
    op.create_index(op.f("ix_outbreaks_location_id"), "outbreaks", ["location_id"], unique=False)
    op.create_table(
        "refresh_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("rotated_from_id", sa.Uuid(), nullable=True),
        sa.Column("device_id", sa.String(length=160), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reuse_detected", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["rotated_from_id"], ["refresh_sessions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_sessions_family_id"), "refresh_sessions", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_sessions_user_id"), "refresh_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "risk_rule_packs",
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["published_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "staff_geographic_assignments",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_staff_geographic_assignments_user_id"),
        "staff_geographic_assignments",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_staff_one_active_assignment",
        "staff_geographic_assignments",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("active = true"),
    )
    op.create_table(
        "triage_rule_packs",
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["published_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "herds",
        sa.Column("farm_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("species", sa.String(length=40), nullable=False),
        sa.Column("animal_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("animal_count >= 0", name="ck_herds_animal_count_nonnegative"),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_herds_farm_id"), "herds", ["farm_id"], unique=False)
    op.create_table(
        "outbreak_transitions",
        sa.Column("outbreak_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("from_state", sa.String(length=20), nullable=False),
        sa.Column("to_state", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["outbreak_id"], ["outbreaks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbreak_transitions_outbreak_id"),
        "outbreak_transitions",
        ["outbreak_id"],
        unique=False,
    )
    op.create_table(
        "animals",
        sa.Column("farm_id", sa.Uuid(), nullable=False),
        sa.Column("herd_id", sa.Uuid(), nullable=True),
        sa.Column("tag_number", sa.String(length=100), nullable=True),
        sa.Column("species", sa.String(length=40), nullable=False),
        sa.Column("sex", sa.String(length=16), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["herd_id"], ["herds.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("farm_id", "tag_number", name="uq_animals_farm_tag"),
    )
    op.create_index(op.f("ix_animals_farm_id"), "animals", ["farm_id"], unique=False)
    op.create_index(op.f("ix_animals_herd_id"), "animals", ["herd_id"], unique=False)
    op.create_table(
        "disease_reports",
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("client_generated_id", sa.Uuid(), nullable=False),
        sa.Column("farm_id", sa.Uuid(), nullable=False),
        sa.Column("animal_id", sa.Uuid(), nullable=True),
        sa.Column("herd_id", sa.Uuid(), nullable=True),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("location_path", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("species", sa.String(length=40), nullable=False),
        sa.Column("affected_count", sa.Integer(), nullable=False),
        sa.Column("mortality_count", sa.Integer(), nullable=False),
        sa.Column("onset_date", sa.Date(), nullable=False),
        sa.Column(
            "report_geometry",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("status IN ('DRAFT', 'SUBMITTED', 'AMENDED')", name="ck_reports_status"),
        sa.CheckConstraint("affected_count >= 1", name="ck_reports_affected_positive"),
        sa.CheckConstraint(
            "mortality_count <= affected_count", name="ck_reports_mortality_not_above_affected"
        ),
        sa.CheckConstraint("mortality_count >= 0", name="ck_reports_mortality_nonnegative"),
        sa.ForeignKeyConstraint(["animal_id"], ["animals.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["herd_id"], ["herds.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reporter_id", "client_generated_id", name="uq_reports_reporter_client_id"
        ),
    )
    op.create_index(
        op.f("ix_disease_reports_farm_id"), "disease_reports", ["farm_id"], unique=False
    )
    op.create_index(
        op.f("ix_disease_reports_location_id"), "disease_reports", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_disease_reports_location_path"), "disease_reports", ["location_path"], unique=False
    )
    op.create_index(
        op.f("ix_disease_reports_onset_date"), "disease_reports", ["onset_date"], unique=False
    )
    op.create_index(
        op.f("ix_disease_reports_reporter_id"), "disease_reports", ["reporter_id"], unique=False
    )
    op.create_index(
        op.f("ix_disease_reports_species"), "disease_reports", ["species"], unique=False
    )
    op.create_index(
        "ix_reports_geometry_gist",
        "disease_reports",
        ["report_geometry"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "ix_reports_status_onset", "disease_reports", ["status", "onset_date"], unique=False
    )
    op.create_table(
        "attachments",
        sa.Column("disease_report_id", sa.Uuid(), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("detected_mime_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("scan_status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "scan_status IN ('PENDING', 'CLEAN', 'REJECTED')", name="ck_attachments_scan_status"
        ),
        sa.CheckConstraint("size_bytes > 0", name="ck_attachments_size_positive"),
        sa.ForeignKeyConstraint(["disease_report_id"], ["disease_reports.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
    )
    op.create_index(
        op.f("ix_attachments_disease_report_id"), "attachments", ["disease_report_id"], unique=False
    )
    op.create_table(
        "case_review_grants",
        sa.Column("grantee_id", sa.Uuid(), nullable=False),
        sa.Column("disease_report_id", sa.Uuid(), nullable=False),
        sa.Column("granted_by_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["disease_report_id"], ["disease_reports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["granted_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["grantee_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "grantee_id", "disease_report_id", "expires_at", name="uq_case_review_grant_window"
        ),
    )
    op.create_table(
        "disease_report_symptoms",
        sa.Column("disease_report_id", sa.Uuid(), nullable=False),
        sa.Column("symptom_id", sa.Uuid(), nullable=False),
        sa.Column("symptom_code_snapshot", sa.String(length=60), nullable=False),
        sa.Column("severity_snapshot", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["disease_report_id"], ["disease_reports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["symptom_id"], ["symptoms.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_disease_report_symptoms_disease_report_id"),
        "disease_report_symptoms",
        ["disease_report_id"],
        unique=False,
    )
    op.create_table(
        "outbreak_report_memberships",
        sa.Column("outbreak_id", sa.Uuid(), nullable=False),
        sa.Column("disease_report_id", sa.Uuid(), nullable=False),
        sa.Column("distance_km", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("included_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("distance_km >= 0", name="ck_outbreak_distance_nonnegative"),
        sa.ForeignKeyConstraint(["disease_report_id"], ["disease_reports.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["outbreak_id"], ["outbreaks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "outbreak_id", "disease_report_id", name="uq_outbreak_report_membership"
        ),
    )
    op.create_table(
        "report_context_snapshots",
        sa.Column("disease_report_id", sa.Uuid(), nullable=False),
        sa.Column("vaccination", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("treatment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("environment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["disease_report_id"], ["disease_reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("disease_report_id"),
    )
    op.create_table(
        "risk_scores",
        sa.Column("disease_report_id", sa.Uuid(), nullable=False),
        sa.Column("rule_pack_id", sa.Uuid(), nullable=False),
        sa.Column("rule_pack_version", sa.String(length=80), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("data_confidence", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("missing_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("invoked_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "category IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name="ck_risk_category"
        ),
        sa.CheckConstraint("data_confidence BETWEEN 0 AND 1", name="ck_risk_confidence_range"),
        sa.CheckConstraint("value BETWEEN 0 AND 100", name="ck_risk_value_range"),
        sa.ForeignKeyConstraint(["disease_report_id"], ["disease_reports.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["invoked_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["rule_pack_id"], ["risk_rule_packs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "disease_report_id", "snapshot_hash", "rule_pack_version", name="uq_risk_replay"
        ),
    )
    op.create_index(
        "ix_risk_category_created", "risk_scores", ["category", "created_at"], unique=False
    )
    op.create_index(op.f("ix_risk_scores_category"), "risk_scores", ["category"], unique=False)
    op.create_index(
        op.f("ix_risk_scores_disease_report_id"), "risk_scores", ["disease_report_id"], unique=False
    )
    op.create_table(
        "triage_results",
        sa.Column("disease_report_id", sa.Uuid(), nullable=False),
        sa.Column("rule_pack_id", sa.Uuid(), nullable=False),
        sa.Column("rule_pack_version", sa.String(length=80), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("suspected_diseases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contributing_factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommended_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_confidence", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("disclaimer", sa.String(length=240), nullable=False),
        sa.Column("invoked_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("data_confidence BETWEEN 0 AND 1", name="ck_triage_confidence_range"),
        sa.ForeignKeyConstraint(["disease_report_id"], ["disease_reports.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["invoked_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["rule_pack_id"], ["triage_rule_packs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "disease_report_id", "snapshot_hash", "rule_pack_version", name="uq_triage_replay"
        ),
    )
    op.create_index(
        op.f("ix_triage_results_disease_report_id"),
        "triage_results",
        ["disease_report_id"],
        unique=False,
    )
    op.create_table(
        "veterinary_cases",
        sa.Column("disease_report_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_veterinarian_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("escalation_reason", sa.String(length=500), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('OPEN', 'IN_REVIEW', 'REFERRED', 'CLOSED')",
            name="ck_veterinary_cases_status",
        ),
        sa.ForeignKeyConstraint(["assigned_veterinarian_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["disease_report_id"], ["disease_reports.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_veterinary_cases_assigned_veterinarian_id"),
        "veterinary_cases",
        ["assigned_veterinarian_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_veterinary_cases_disease_report_id"),
        "veterinary_cases",
        ["disease_report_id"],
        unique=False,
    )
    op.create_index(
        "uq_open_case_per_report",
        "veterinary_cases",
        ["disease_report_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'CLOSED'"),
    )
    op.create_table(
        "alerts",
        sa.Column("disease_report_id", sa.Uuid(), nullable=False),
        sa.Column("risk_score_id", sa.Uuid(), nullable=True),
        sa.Column("recipient_id", sa.Uuid(), nullable=True),
        sa.Column("alert_type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name="ck_alerts_severity"
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'ACKNOWLEDGED', 'CLOSED')", name="ck_alerts_status"
        ),
        sa.ForeignKeyConstraint(["disease_report_id"], ["disease_reports.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["risk_score_id"], ["risk_scores.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alerts_disease_report_id"), "alerts", ["disease_report_id"], unique=False
    )
    op.create_index(op.f("ix_alerts_recipient_id"), "alerts", ["recipient_id"], unique=False)
    op.create_index(
        "uq_active_risk_alert",
        "alerts",
        ["disease_report_id", "alert_type"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "risk_factor_contributions",
        sa.Column("risk_score_id", sa.Uuid(), nullable=False),
        sa.Column("factor", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=160), nullable=False),
        sa.Column("normalized_value", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("weight", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("points", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "normalized_value BETWEEN 0 AND 1", name="ck_risk_factor_normalized_range"
        ),
        sa.CheckConstraint("weight BETWEEN 0 AND 1", name="ck_risk_factor_weight_range"),
        sa.ForeignKeyConstraint(["risk_score_id"], ["risk_scores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_factor_contributions_risk_score_id"),
        "risk_factor_contributions",
        ["risk_score_id"],
        unique=False,
    )
    op.create_table(
        "triage_findings",
        sa.Column("triage_result_id", sa.Uuid(), nullable=False),
        sa.Column("disease_code", sa.String(length=60), nullable=False),
        sa.Column("evidence_code", sa.String(length=100), nullable=False),
        sa.Column("evidence_kind", sa.String(length=20), nullable=False),
        sa.Column("matched", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=7, scale=5), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "evidence_kind IN ('POSITIVE', 'NEGATIVE', 'MISSING')", name="ck_triage_findings_kind"
        ),
        sa.ForeignKeyConstraint(["triage_result_id"], ["triage_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_triage_findings_triage_result_id"),
        "triage_findings",
        ["triage_result_id"],
        unique=False,
    )
    report_access_predicate = """
    (
      'ADMIN' = ANY(string_to_array(coalesce(current_setting('app.roles', true), ''), ','))
      OR reporter_id = nullif(current_setting('app.user_id', true), '')::uuid
      OR (
        ('VETERINARIAN' = ANY(string_to_array(coalesce(current_setting('app.roles', true), ''), ','))
         OR 'PARAVET' = ANY(string_to_array(coalesce(current_setting('app.roles', true), ''), ',')))
        AND location_path LIKE coalesce(current_setting('app.location_path', true), '') || '%'
        AND coalesce(current_setting('app.location_path', true), '') <> ''
      )
      OR (
        'DISTRICT_OFFICER' = ANY(string_to_array(coalesce(current_setting('app.roles', true), ''), ','))
        AND EXISTS (
          SELECT 1 FROM case_review_grants review_grant
          WHERE review_grant.disease_report_id = disease_reports.id
            AND review_grant.grantee_id = nullif(current_setting('app.user_id', true), '')::uuid
            AND review_grant.revoked_at IS NULL
            AND review_grant.expires_at > now()
        )
      )
    )
    """
    report_write_predicate = """
    (
      'ADMIN' = ANY(string_to_array(coalesce(current_setting('app.roles', true), ''), ','))
      OR reporter_id = nullif(current_setting('app.user_id', true), '')::uuid
      OR (
        ('VETERINARIAN' = ANY(string_to_array(coalesce(current_setting('app.roles', true), ''), ','))
         OR 'PARAVET' = ANY(string_to_array(coalesce(current_setting('app.roles', true), ''), ',')))
        AND location_path LIKE coalesce(current_setting('app.location_path', true), '') || '%'
        AND coalesce(current_setting('app.location_path', true), '') <> ''
      )
    )
    """
    op.execute("ALTER TABLE disease_reports ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE disease_reports FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY disease_reports_select ON disease_reports "
        f"FOR SELECT USING {report_access_predicate}"
    )
    op.execute(
        f"CREATE POLICY disease_reports_insert ON disease_reports "
        f"FOR INSERT WITH CHECK {report_write_predicate}"
    )
    op.execute(
        f"CREATE POLICY disease_reports_update ON disease_reports "
        f"FOR UPDATE USING {report_write_predicate} WITH CHECK {report_write_predicate}"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS disease_reports_update ON disease_reports")
    op.execute("DROP POLICY IF EXISTS disease_reports_insert ON disease_reports")
    op.execute("DROP POLICY IF EXISTS disease_reports_select ON disease_reports")
    op.drop_index(op.f("ix_triage_findings_triage_result_id"), table_name="triage_findings")
    op.drop_table("triage_findings")
    op.drop_index(
        op.f("ix_risk_factor_contributions_risk_score_id"), table_name="risk_factor_contributions"
    )
    op.drop_table("risk_factor_contributions")
    op.drop_index(
        "uq_active_risk_alert", table_name="alerts", postgresql_where=sa.text("status = 'ACTIVE'")
    )
    op.drop_index(op.f("ix_alerts_recipient_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_disease_report_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(
        "uq_open_case_per_report",
        table_name="veterinary_cases",
        postgresql_where=sa.text("status <> 'CLOSED'"),
    )
    op.drop_index(op.f("ix_veterinary_cases_disease_report_id"), table_name="veterinary_cases")
    op.drop_index(
        op.f("ix_veterinary_cases_assigned_veterinarian_id"), table_name="veterinary_cases"
    )
    op.drop_table("veterinary_cases")
    op.drop_index(op.f("ix_triage_results_disease_report_id"), table_name="triage_results")
    op.drop_table("triage_results")
    op.drop_index(op.f("ix_risk_scores_disease_report_id"), table_name="risk_scores")
    op.drop_index(op.f("ix_risk_scores_category"), table_name="risk_scores")
    op.drop_index("ix_risk_category_created", table_name="risk_scores")
    op.drop_table("risk_scores")
    op.drop_table("report_context_snapshots")
    op.drop_table("outbreak_report_memberships")
    op.drop_index(
        op.f("ix_disease_report_symptoms_disease_report_id"), table_name="disease_report_symptoms"
    )
    op.drop_table("disease_report_symptoms")
    op.drop_table("case_review_grants")
    op.drop_index(op.f("ix_attachments_disease_report_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index("ix_reports_status_onset", table_name="disease_reports")
    op.drop_index("ix_reports_geometry_gist", table_name="disease_reports", postgresql_using="gist")
    op.drop_index(op.f("ix_disease_reports_species"), table_name="disease_reports")
    op.drop_index(op.f("ix_disease_reports_reporter_id"), table_name="disease_reports")
    op.drop_index(op.f("ix_disease_reports_onset_date"), table_name="disease_reports")
    op.drop_index(op.f("ix_disease_reports_location_path"), table_name="disease_reports")
    op.drop_index(op.f("ix_disease_reports_location_id"), table_name="disease_reports")
    op.drop_index(op.f("ix_disease_reports_farm_id"), table_name="disease_reports")
    op.drop_table("disease_reports")
    op.drop_index(op.f("ix_animals_herd_id"), table_name="animals")
    op.drop_index(op.f("ix_animals_farm_id"), table_name="animals")
    op.drop_table("animals")
    op.drop_index(op.f("ix_outbreak_transitions_outbreak_id"), table_name="outbreak_transitions")
    op.drop_table("outbreak_transitions")
    op.drop_index(op.f("ix_herds_farm_id"), table_name="herds")
    op.drop_table("herds")
    op.drop_table("user_roles")
    op.drop_table("triage_rule_packs")
    op.drop_index(
        "uq_staff_one_active_assignment",
        table_name="staff_geographic_assignments",
        postgresql_where=sa.text("active = true"),
    )
    op.drop_index(
        op.f("ix_staff_geographic_assignments_user_id"), table_name="staff_geographic_assignments"
    )
    op.drop_table("staff_geographic_assignments")
    op.drop_table("risk_rule_packs")
    op.drop_index(op.f("ix_refresh_sessions_user_id"), table_name="refresh_sessions")
    op.drop_index(op.f("ix_refresh_sessions_family_id"), table_name="refresh_sessions")
    op.drop_table("refresh_sessions")
    op.drop_index(op.f("ix_outbreaks_location_id"), table_name="outbreaks")
    op.drop_index(op.f("ix_outbreaks_disease_code"), table_name="outbreaks")
    op.drop_index("ix_outbreak_state_created", table_name="outbreaks")
    op.drop_index("ix_outbreak_geometry_gist", table_name="outbreaks", postgresql_using="gist")
    op.drop_table("outbreaks")
    op.drop_table("mfa_credentials")
    op.drop_index(op.f("ix_farms_owner_id"), table_name="farms")
    op.drop_index(op.f("ix_farms_location_id"), table_name="farms")
    op.drop_index("ix_farms_geometry_gist", table_name="farms", postgresql_using="gist")
    op.drop_table("farms")
    op.drop_table("disease_symptoms")
    op.drop_table("auth_identities")
    op.drop_table("users")
    op.drop_table("symptoms")
    op.drop_table("roles")
    op.drop_index("ix_outbox_pending", table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_topic"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_aggregate_id"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(op.f("ix_locations_hierarchy_path"), table_name="locations")
    op.drop_index("ix_locations_geometry_gist", table_name="locations", postgresql_using="gist")
    op.drop_table("locations")
    op.drop_table("idempotency_receipts")
    op.drop_table("diseases")
    op.drop_index("ix_audit_resource", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
